{{- if .Values.proxies }}
---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-ssh-keys
  namespace: {{ .Values.crawler_namespace }}
#type: kubernetes.io/ssh-auth
type: Opaque
stringData:
{{- range .Values.proxies }}
  {{ .id }}-private-key: |
{{ .private_key | indent 4 }}
  {{ .id }}-known-hosts: {{ .host_public_key }}
{{- end }}

  # slightly hacky: override /etc/passwd and /etc/group in crawler to be able to ssh to proxies
  passwd: |
    root:x:0:0:root:/root:/bin/bash
    btrix:btrix:{{ .Values.crawler_uid | default 201407 }}:{{ .Values.crawler_gid | default 201407 }}::/tmp/btrix:/bin/sh

  group: |
    root:x:0:
    btrix:x:{{ .Values.crawler_gid | default 201407 }}:

{{- end }}

