{{- if .Values.proxies }}
---
apiVersion: v1
kind: Secret
metadata:
  name: proxies
  namespace: {{ .Values.crawler_namespace }}
type: Opaque
stringData:
{{- range .Values.proxies }}

{{- if .ssh_private_key }}
  {{ .id }}-private-key: |
{{ .ssh_private_key | indent 4 }}
{{- end }}

{{- if .ssh_host_public_key }}
  {{ .id }}-known-hosts: |
{{ .ssh_host_public_key | indent 4 }}
{{- end }}

{{- end }}

  # slightly hacky: override /etc/passwd and /etc/group in crawler to be able to ssh to proxies
  passwd: |
    root:x:0:0:root:/root:/bin/bash
    btrix:btrix:{{ .Values.crawler_uid | default 201407 }}:{{ .Values.crawler_gid | default 201407 }}::/tmp/btrix:/bin/sh

  group: |
    root:x:0:
    btrix:x:{{ .Values.crawler_gid | default 201407 }}:

---
apiVersion: v1
kind: Secret
metadata:
  name: ops-proxy-configs
  namespace: {{ .Release.Namespace }}

type: Opaque
data:
  crawler_proxies_last_update: {{ now | unixEpoch | toString | b64enc | quote }}
  crawler_proxies.json: {{ .Values.proxies | toJson | b64enc | quote }}
{{- end }}
